apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: testprmar6-1
  janus-idp.io/tekton: testprmar6-1
  backstage.io/kubernetes-id: testprmar6-1
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: testprmar6-1
resources:
  - initialize-namespace.yaml
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
